image: node:latest

stages:
  - install
  - build
  - quality
  - test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

install:
  stage: install
  script:
    - npm install
  artifacts:
    name: "artifacts"
    untracked: true
    expire_in: 30 mins
    paths:
      - .npm/
      - node_modules/

build:
  stage: build
  script:
    - CI=false npm run build
  artifacts:
    paths:
      - build
    expire_in: 30 mins
  dependencies:
    - install

linting:
  stage: quality
  script:
    - npm run lint
  dependencies:
    - install

format:
  stage: quality
  script:
    - sed -i 's/crlf/lf/g' biome.json
    - npm run format
  dependencies:
    - install

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml

