import './globals.css'
import Navbar from "./components/Navbar";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
      <head />
      <body suppressHydrationWarning={ true } className="bg-slate-800">
        <Navbar />
        { children }
      </body>
    </html>
  )
}
